export default[
    {
        question:1,
        options:[1,2,3,4],
        answer:0
    },
    {
        question:2,
        options:[1,2,3,4],
        answer:0
    },
    {
        question:3,
        options:[1,2,3,4],
        answer:0
    },
    {
        question:4,
        options:[1,2,3,4],
        answer:0
    },
    {
        question:5,
        options:[1,2,3,4],
        answer:0
    },
]